### ISSUE TITLE
真正的`服务层`是怎么写的? - 三·钻 TriDiamond

### ISSUE THREAD

**Issue by bennyxguo** [bennyxguo/blog-comments#12]
https://tridiamond.me/2019/10/19/backend/how-to-write-a-service.html

**Comment by cxinxy** [comment]
主题很好看

**Comment by bennyxguo** [comment]
> @IDeepspace
> 主题很好看

谢谢支持

**Comment by xzhuz** [comment]
今年看到最惊艳的一个主题了

**Comment by zenwan** [comment]
惊艳！
测试下是否支持数学公式
$$% \f is defined as f(#1) using the macro
\f{x} = \int_{-\infty}^\infty
    \hat \f\xi\,e^{2 \pi i \xi x}
    \,d\xi$$

**Comment by zenwan** [comment]
好像不支持数学公式  https://katex.org/

**Comment by forrany** [comment]
惊艳了

**Comment by GenesisLQ** [comment]
代码高亮不会弄啊

**Comment by bennyxguo** [comment]
> @GenesisLQ
> 代码高亮不会弄啊

在你hexo博客的根目录的`_config.yml`里面搜索**highlight**（记住不是主题里面的`_config.yml`）。
这个改好了，重新生成文件就好了。
```bash
hexo clean && hexo g
```

**Comment by weteghter** [comment]
超级炫酷
