### ISSUE TITLE
JavaScript中更简便的数组处理函数- 使用.map()，.reduce()，.filter() - 三·钻 TriDiamond

### ISSUE THREAD

**Issue by bennyxguo** [bennyxguo/blog-comments#14]
https://tridiamond.me/2019/11/02/frontend/simplify-your-javascript-with.html

**Comment by heihuafeifahui** [comment]
111

**Comment by itaiit** [comment]
博客好酷炫~~，都是自己的灵感吗~

**Comment by bennyxguo** [comment]
> @itaiit
> 博客好酷炫~~，都是自己的灵感吗~

- 集合了很多自己的设计和看过很多网站的优点，加上现在流行的一些设计和黑色主题的崛起
- 还有很多自己在做网站和系统时候的灵感也发挥在这个博客主题的设计里面
- 很多这个主题里面的设计和样式都是自己的经验和灵感中打造出来的

> 一开始的主要灵感来源是[CSS-Tricks](https://css-tricks.com/)

**Comment by zenwan** [comment]
$\tilde{C}_{t}$

**Comment by zenwan** [comment]
$$ \tilde{C}_{t}$$

**Comment by orzklv** [comment]
C'mon obisidan theme comment gitalk here is workin' but not in my

**Comment by kaerba** [comment]
你的主题克隆到本地之后报错了 大兄弟

**Comment by bennyxguo** [comment]
@WYIRANXS 具体报什么错误呢？

**Comment by bennyxguo** [comment]
@sakhib-orzklv How is it not working do you have a setup online website? or do you see any console errors?

**Comment by zjxjwxk** [comment]
Test

**Comment by Lauweal** [comment]
大佬，主题下下来提示htmlTruncate is not defined

**Comment by jeth123** [comment]
支持大佬！！！主题太帅了。有大佬的主题搭了个blog，遇到些小问题，还好都解决了。借大佬楼展示下成果，与打偶问题可以一起交流，我也是才入坑。[我的博客](https://jeth123.gitee.io)

**Comment by L3sliez** [comment]
> @MC-LiuWei
> 大佬，主题下下来提示htmlTruncate is not defined

你需要下载hexo-html-truncate插件支持，配置文件中有

·# Enable html truncate

·# see https://github.com/TriDiamond/hexo-html-truncate

在本地文件中使用npm下载就可以了。

**Comment by ghost** [comment]
我有几个问题，提在 `Github issue` 里面：
<a href="https://github.com/TriDiamond/hexo-theme-obsidian/issues/76">遇到几个问题 #76</a>

**Comment by leolin-idah** [comment]
您好，我想重写发布可以吗
