### ISSUE TITLE
一篇文章搞懂前端学习方法与构建知识体系 - 三·钻 TriDiamond

### ISSUE THREAD

**Issue by bennyxguo** [bennyxguo/blog-comments#29]
https://tridiamond.me/2020/08/07/frontend/frontend-study.html 

 前沿在大前端的成长路上，很多的同学都非常的迷茫，看到一座座越来越高的山。慢慢在工作中也对自己的职业发展也特别迷茫。有些粉丝也私信我问过我一些职业发展的问题，还有“我应该学习什么技术？”，“学习到什么,

**Comment by Axton-Tang** [comment]
测试一下评论，哈哈
